export WINE_APP_PATH="$HOME/Wine/apps/test-app.app"
export WINE_APP_CONTENTS_PATH="$WINE_APP_PATH/Contents"
export WINE_CONFIG_APP_NAME="config-app"
export WINE_CONFIG_APP_PATH="$WINE_APP_PATH/$WINE_CONFIG_APP_NAME.app"
export WINE_APP_SCRIPTS_PATH="$WINE_CONFIG_APP_PATH/Contents/Resources/bash"
export WINE_APP_SHARED_SUPPORT_PATH=$WINE_APP_CONTENTS_PATH/SharedSupport
export WINE_APP_PREFIX_PATH=$WINE_APP_SHARED_SUPPORT_PATH/prefix