export * from './AppIcon';
export * from './CreateAppIcon';
export * from './HomeIcon';
export * from './InstallIcon';
export * from './PlayIcon';
export * from './RegeditIcon';
export * from './SettingsIcon';
export * from './TasksIcon';
export * from './XCircleIcon';
