export type BashScript =
  | 'buildUniqueAppName'
  | 'bundleApp'
  | 'cmd'
  | 'scaffoldApp'
  | 'extractWineEngine'
  | 'listAppExecutables'
  | 'loadDylibs'
  | 'regedit'
  | 'taskmgr'
  | 'uninstaller'
  | 'wine'
  | 'wineboot'
  | 'winecfg'
  | 'winefile'
  | 'winetrick'
  | 'winetricks';
